# Generated by Django 4.1.1 on 2022-09-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='like_n',
        ),
    ]
