# Generated by Django 4.0.7 on 2022-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='aid',
            field=models.CharField(max_length=20, unique=True, verbose_name='视频aid'),
        ),
        migrations.AlterField(
            model_name='info',
            name='cid',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='视频cid'),
        ),
    ]
