# Generated by Django 4.1.1 on 2022-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_like_comment_like_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=300, verbose_name='评论内容'),
        ),
    ]
