# Generated by Django 4.1.1 on 2022-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_danmu_ctime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_hotwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(verbose_name='评论编号')),
                ('hot_word', models.CharField(max_length=10, verbose_name='评论内容')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('update_time', models.IntegerField(verbose_name='更新时间')),
                ('create_time', models.IntegerField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Danmu_hotwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(verbose_name='danmu编号')),
                ('hot_word', models.CharField(max_length=10, verbose_name='damu内容')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('update_time', models.IntegerField(verbose_name='更新时间')),
                ('create_time', models.IntegerField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
