# Generated by Django 4.1.1 on 2022-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_comment_hotwords_danmu_hotwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_hotwords',
            name='create_time',
            field=models.CharField(max_length=10, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment_hotwords',
            name='update_time',
            field=models.CharField(max_length=10, verbose_name='更新时间'),
        ),
    ]
