# Generated by Django 4.1.1 on 2022-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_comment_hotwords_create_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_hotwords',
            options={'verbose_name': '评论热词', 'verbose_name_plural': '评论热词'},
        ),
        migrations.AlterModelOptions(
            name='danmu_hotwords',
            options={'verbose_name': '弹幕热词', 'verbose_name_plural': '弹幕热词'},
        ),
        migrations.AlterField(
            model_name='danmu_hotwords',
            name='create_time',
            field=models.CharField(max_length=10, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='danmu_hotwords',
            name='update_time',
            field=models.CharField(max_length=10, verbose_name='更新时间'),
        ),
    ]
