# Generated by Django 4.1.1 on 2022-09-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_alter_comment_hotwords_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danmu_hotwords',
            name='cid',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, related_name='danmu_hotword', to='note.info', to_field='cid'),
        ),
    ]
