# Generated by Django 4.1.1 on 2022-09-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_alter_comment_hotwords_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '笔记', 'verbose_name_plural': '笔记'},
        ),
    ]
