# Generated by Django 4.0.7 on 2022-10-06 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KolFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户达人收藏',
                'verbose_name_plural': '用户达人收藏',
            },
        ),
        migrations.CreateModel(
            name='NoteFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('notes', models.ForeignKey(help_text='笔记id', on_delete=django.db.models.deletion.CASCADE, to='note.info', verbose_name='笔记')),
            ],
            options={
                'verbose_name': '用户笔记收藏',
                'verbose_name_plural': '用户笔记收藏',
            },
        ),
    ]
