# Generated by Django 4.1.1 on 2022-09-23 05:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kol', '0002_initial'),
        ('note', '0011_alter_info_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('notes', models.ForeignKey(help_text='笔记id', on_delete=django.db.models.deletion.CASCADE, to='note.info', verbose_name='笔记')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户笔记收藏',
                'verbose_name_plural': '用户笔记收藏',
                'unique_together': {('user', 'notes')},
            },
        ),
        migrations.CreateModel(
            name='KolFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('kols', models.ForeignKey(help_text='商品id', on_delete=django.db.models.deletion.CASCADE, to='kol.info', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户达人收藏',
                'verbose_name_plural': '用户达人收藏',
                'unique_together': {('user', 'kols')},
            },
        ),
    ]
