# Generated by Django 4.1.1 on 2022-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vip',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, 'vip'), (2, 'svip'), (3, 'sss')], default=0),
        ),
    ]
