# Generated by Django 4.0.7 on 2022-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='mid',
            field=models.CharField(max_length=20, unique=True, verbose_name='up主编号'),
        ),
    ]
